# 1. Используем официальный Node.js образ
FROM node:21-alpine

# 2. Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# 3. Копируем package.json и package-lock.json
COPY package.json ./
COPY package-lock.json ./

# 4. Устанавливаем зависимости
RUN npm install

# 5. Копируем весь проект
COPY . ./

# 6. Указываем команду для запуска приложения
CMD ["npm", "start"]
